backend:
  name: github
  repo: shredtechular/seekhealing.github.io
  branch: refactor
  site_domain: seekhealing-refactor.netlify.com
publish_mode: editorial_workflow
media_folder: "/assets/images"
collections:
  - name: "post" # Used in routes, e.g. /admin/collections/blog
    label: "Post" # Used in the UI
    folder: "_posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template i.e. YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "page" # Used in routes, e.g. /admin/collections/blog
    label: "Page" # Used in the UI
    folder: "_pages" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template 
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
      - {label: "Permalink", name: "permalink", widget: "hidden", default: ""}
      - {label: "Title", name: "title", widget: "string"}
      - label: "Sections"
        name: "sections"
        widget: "list"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - label: "Type"
            name: "type"
            widget: "select"
            options: ["article", "citation", "connect", "connection-agent-form", "double", "double-full", "events", "gauges", "hero", "locations", "memorial-wall", "message-box", "parallax", "resource", "single", "stories", "stripe", "subnav", "subscribe", "team", "triple"]
      - {label: "Transparent Header?", name: "transparent-header", widget: "boolean", default: false}
      - {label: "Body", name: "body", widget: "markdown", required: false}
  - name: "otherContent" 
    label: "Miscellaneous Content" 
    delete: false # Prevent users from deleting documents in this collection
    editor: 
      preview: false 
    files: 
      - name: "global" 
        label: "Global Site Content" 
        file: "_data/global.yaml" 
        description: "Global content" 
        fields: 
          - {label: "Email Address", name: "email", widget: "string"}
          - {label: "Email Icon", name: "email-icon", widget: "string"}
          - {label: "Subscribe Form Submission URL", name: "subscribe-url", widget: "string"}
          - {label: "Subscribe Form Text", name: "subscribe-text", widget: "string"}
          - {label: "Subscribe Form Button Text", name: "subscribe-btn-text", widget: "string"}
      - name: "header" 
        label: "Header Content" 
        file: "_data/header.yaml" 
        description: "Header content" 
        fields: 
          - label: "Logo Image"
            name: "logo"
            widget: "image"
          - {label: "Logo Alt Text", name: "logo-alt", widget: "string"}
          - label: "Header Navigation Items" 
            name: nav 
            widget: "list" 
            fields: 
              - {label: "Title", name: title, widget: string}
              - {label: "URL", name: url, widget: string}
              - label: "Target"
                name: target
                widget: select
                options: ["", "_blank"]
              - label: "SubMenu"
                name: submenu
                widget: list
                fields:
                  - {label: "Title", name: title, widget: string}
                  - {label: "URL", name: url, widget: string}
                  - label: "Target"
                    name: target
                    widget: select
                    options: ["", "_blank"]
      - name: "footer" 
        label: "Footer Content" 
        file: "_data/footer.yaml" 
        description: "Footer content" 
        fields: 
          - {label: "Copyright Text", name: "copyright-text", widget: "string"}
          - label: "Footer Navigation Items" 
            name: nav 
            widget: "list" 
            fields: 
              - {label: "Title", name: title, widget: string}
              - {label: "URL", name: url, widget: string}
              - label: "Target"
                name: target
                widget: select
                options: ["", "_blank"]
          - label: "Footer Social Media Links" 
            name: "social-media"
            widget: "list"
            fields: 
              - {label: "Icon class", name: icon, widget: string}
              - {label: "URL", name: url, widget: string}
      - name: "contact" 
        label: "Contact Page Content" 
        file: "_data/contact.yaml" 
        description: "Contact Page content" 
        fields: 
          - {label: "Contact Header", name: "location-header", widget: "string"}
          - label: "Location Contacts" 
            name: location-contacts 
            widget: "list"
            fields:
              - {label: "City", name: city, widget: string}
              - {label: "State", name: state, widget: string}
              - {label: "Contact Email Address", name: email, widget: string}
          - {label: "Connect Header", name: "connect-header", widget: "string"}
      - name: "memorial-wall"
        label: "Memorial Wall Memorium" 
        file: "_data/memorial-wall.yaml" 
        description: "People listed on the Memorial Wall" 
        fields: 
          - label: "In Memorium" 
            name: memorium
            widget: "list"
            fields:
              - {label: "Name", name: name, widget: string}
              - {label: "Remembered By", name: remembered-by, widget: string}
              - {label: "Quote", name: quote, widget: string}
      - name: "resources"
        label: "Resources" 
        file: "_data/resources.yaml" 
        description: "List of resources used in site" 
        fields: 
          - label: "Resources" 
            name: resources
            widget: "list"
            fields:
              - {label: "Title", name: title, widget: string}
              - {label: "Sub-title", name: subtext, widget: string}
              - {label: "Link", name: url, widget: string}
              - {label: "Icon", name: icon, widget: string}
              - label: "Target"
                name: target
                widget: select
                options: ["", "_blank"]
      - name: "asheville-pilot-program"
        label: "Asheville Pilot Content" 
        file: "_data/asheville-pilot-program.yaml" 
        description: "Content for Asheville Pilot Program Page" 
        fields: 
          - {label: "header", name: header, widget: string}
          - {label: "Subheader", name: subheader, widget: string}
          - {label: "Seeker Image", name: seeker-img, widget: string}
          - {label: "Seeker Image Alt Text", name: seeker-img-alt, widget: string}
          - {label: "Seeker Header", name: seeker-header, widget: string}
          - {label: "Seeker Description", name: seeker-desc, widget: string}
          - {label: "Seeker Image 2", name: seeker-img-2, widget: string}
          - {label: "Seeker Image 2 Alt Text", name: seeker-img-2-alt, widget: string}
          - {label: "Seeker Side Text 1", name: seeker-side-1, widget: string}
          - {label: "Seeker Side Text 2", name: seeker-side-2, widget: string}
          - {label: "Connection Agent Activities Image", name: conn-agent-acts, widget: string}
          - {label: "Connection Agent Activities Image Alt Text", name: conn-agent-acts-alt, widget: string}
          - {label: "Connection Basketball Image", name: conn-bball, widget: string}
          - {label: "Connection Basketball Image Alt Text", name: conn-bball-alt, widget: string}
          - {label: "Connection Agent Header", name: conn-agent-header, widget: string}
          - {label: "Connection Agent Description", name: conn-agent-desc, widget: string}
          - {label: "Connection Gathering Image", name: conn-gathering, widget: string}
          - {label: "Connection Gathering Image Alt Text", name: conn-gathering-alt, widget: string}
          - {label: "Connection Gathering Header", name: conn-gathering-header, widget: string}
          - {label: "Connection Gathering Description", name: conn-gathering-desc, widget: string}
          - {label: "Big Stick Figure Image", name: big-stick, widget: string}
          - {label: "Big Stick Figure Image Alt Text", name: big-stick-alt, widget: string}
          - {label: "Match text", name: match, widget: string}
          - {label: "Match Image", name: match-img, widget: string}
          - {label: "Match Image Alt Text", name: match-img-alt, widget: string}
          - {label: "Match Description", name: match-desc, widget: string}
          - {label: "Match Description 2", name: match-desc-2, widget: string}
          - {label: "Yoga Image", name: yoga, widget: string}
          - {label: "Yoga Image Alt Text", name: yoga-alt, widget: string}
          - {label: "Match Description 3", name: match-desc-3, widget: string}
          - {label: "Data Image", name: data, widget: string}
          - {label: "Data Image Alt Text", name: data-alt, widget: string}
          - {label: "Data Header", name: data-header, widget: string}
          - {label: "Data Description", name: data-desc, widget: string}
          - {label: "Apply Header", name: apply-header, widget: string}
          - label: "Apply Links" 
            name: apply-links
            widget: "list"
            fields:
              - {label: "Description", name: title, widget: string}
              - {label: "URL", name: url, widget: string}
              - {label: "Button Text", name: btn-txt, widget: string}
          - {label: "Sub-Text", name: subtext, widget: string}
  - name: "section-hero" # Used in routes, e.g. /admin/collections/blog
    label: "Section_Hero" # Used in the UI
    folder: "_sections/hero" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template 
    fields: # The fields for each document, usually in front matter
      - {label: "Type", name: "type", widget: "hidden", default: "hero"}
      - label: "Title"
        name: "title"
        widget: "string"
        pattern: ['^[a-zA-Z0-9_\-]+$', "Can not contain whitespace characters.  Alphanumeric and underscores and dashes only."]
      - {label: "Background Image", name: "background", widget: "image", default: "/assets/images/home-bkgrnd.jpg"}
      - {label: "Video URL", name: "video", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "section-team" # Used in routes, e.g. /admin/collections/blog
    label: "Section_Team" # Used in the UI
    folder: "_sections/team" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template 
    fields: # The fields for each document, usually in front matter
      - {label: "Type", name: "type", widget: "hidden", default: "team"}
      - {label: "Category", name: "category", widget: "string", default: "Directors"}
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Job Title", name: "title", widget: "string"}
      - {label: "Director's Picture", name: "image", widget: "image"}
      - {label: "Order", name: "order", widget: "number", valueType: "int", min: "1"}
      - {label: "Body", name: "body", widget: "markdown"}